### ISSUE TITLE
Multi sensor device problems

### ISSUE THREAD

**Issue by Hmbayrakdar** [smart-data-models/Smart-Sensoring#1]
We have a use case where a device contains a total of 10 air quality and weather sensors. If we use this data model of 'Device', the attribute 'value' becomes too crowded and too hard to use. An example screenshot with no encoding is added below.
![Screenshot from 2020-10-13 11-31-48](https://user-images.githubusercontent.com/24212094/95836115-b9719580-0d47-11eb-87f2-7dd449ecc756.png)

If we want to use this data for visualization and other services, we have to differentiate the domains of properties and etc.
There is also the issue where if we try to use the 'Weather' smart data model or 'Air Quality' data model, reusing the 'value' attribute becomes too complex, requiring further services or sending the data from device to these 3 different entities.

**Comment by AHABID** [comment]
Hello, 
I guess that you are using an NGSI-LD data format.
Following the NGSI-LD specification it is possible to create new attributes such as temperature, humidity, windSpeed..... It is also possible to add more metadata such as the unit code (expressed in CEFACT format), or the timeStamp using the NGSI-LD property 'observedAt' expressed in ISO8601 format. Below an example for the property temperature:

`"temperature":{
        "type":"Property", 
         "value":"25",
         "unitCode":"CEL",
         "observedAt":"2020-06-30T11:00:00Z"}`

The issue is that the Device as defined in Fiware Smart data models Schema's does not support these new attributes. I think that this is a limitation for the Device Model that we should take into account in the future. The possible actual solution is to define these new attributes and extend the Device model to support them in your environnement.

**Comment by Hmbayrakdar** [comment]
We were also thinking about extending the model so that each 'controlledProperty' value will have an attribute of its own like you shown. Thanks for the answer!
